### ISSUE TITLE
TestCaseSource and ValueSource statics fixer

### ISSUE THREAD

**Issue by wachulski** [wachulski/nunit-migrator#20]

**Comment by wachulski** [comment]
@mwachulski - please elaborate

**Comment by ChrisMaddock** [comment]
I'm not sure if that's what this issue is for - but would you consider a code fix here, even if it may break compilation?

Making sources static is a big chunk of the migration work we normally need to do - and many can just be made static straight off. (Arguably, in that case, they should have been static from the first place - but that's a different issue!) Having a code fix which can change the 80% fine, and leave me to fix the remaining 20% would be very helpful from out end.

**Comment by wachulski** [comment]
I did it myself once and I totally agree with you @ChrisMaddock . Btw there is a basic scenario and a bit more advanced:

1. Basic: making static only a directly referenced member.
2. Advanced: making static the whole call chain (that is all members that are used to compute the directly referenced member).

I schedule the basic one for development soon, but the advanced scenario - most likely won't pay off.

**Comment by ChrisMaddock** [comment]
I agree. The advance version sounds riskier too - especially if it started involving variables...

Great - thanks!

**Comment by ChrisMaddock** [comment]
Awesome - thanks! Time for an upgrade!
